runtime: python39  # 必須

handlers:
  - url: /css
    static_dir: css

  - url: /img
    static_dir: img

  - url: /js
    static_dir: js

  # flexbox ディレクトリ内の各レッスンページ
  - url: /flexbox/(.*)
    static_files: templates/flexbox/\1
    upload: templates/flexbox/(.*)

  # form ディレクトリ内の各レッスンページ
  - url: /form/(.*)
    static_files: templates/form/\1
    upload: templates/form/(.*)

  # ルートURL（index.html）
  - url: /
    static_files: index.html
    upload: index.html
