runtime: python39  # 必須。Pythonランタイムを指定しますが、スクリプトは不要です。

handlers:
  - url: /css
    static_dir: css

  - url: /img
    static_dir: img

  - url: /js
    static_dir: js

  - url: /.*
    static_files: index.html
    upload: index.html
