runtime: python39

handlers:
  - url: /css
    static_dir: css
  - url: /docs
    static_dir: docs
  - url: /img
    static_dir: img
  - url: /js
    static_dir: js
  - url: /juth
    static_dir: juth
  - url: /templates
    static_dir: templates
  - url: /.*
    static_files: index.html
    upload: index.html
